#---------------------------------------------------------------------------------------------------------
#                                             Server Configuration
#---------------------------------------------------------------------------------------------------------
server:
  port: 8082
  forward-headers-strategy: framework
  
  
  
#-------------------------------------------------------------------------------------------------------------------
#                                             Spring Configuration
#-------------------------------------------------------------------------------------------------------------------
spring:
  application:
    name: content-service

  datasource:
    url: jdbc:postgresql://db-contents:5432/contentsDB
    username: admin
    password: admin

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: 'false'
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update



#-------------------------------------------------------------------------------------------------------------------
#                                             Eureka Configuration
#-------------------------------------------------------------------------------------------------------------------
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}