spring:
  application:
    name: board-service

  datasource:
    url: jdbc:postgresql://db-boards:5432/boardsDB
    username: admin
    password: admin

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: 'false'
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update

  cloud:
    kubernetes:
      enabled: false

server:
  port: 8084
  forward-headers-strategy: framework
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}