spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/api/**]':
            allowedOrigins: "http://localhost:8080"
            allowedHeaders:
              - Content-Type
            allowedMethods:
              - GET
              - POST
              - DELETE
        # add-to-simple-url-handler-mapping: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
            - Query=param
        - id: content-service
          uri: lb://content-service
          predicates:
            - Path=/api/contents/**
        - id: balon-service
          uri: lb://balon-service
          predicates:
            - Path=/api/saleads/**
        - id: board-service
          uri: lb://board-service
          predicates:
            - Path=/api/boards/**

    kubernetes:
      enabled: false
  application:
    name: api-gateway
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}