spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://db-users:5432/usersDB
    username: admin
    password: admin

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: 'false'
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update

  cloud:
    kubernetes:
      enabled: false
  
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 41349424583-le95vivil3e7v5u6iqketi1k6q8stho1.apps.googleusercontent.com
            client-secret: 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

server:
  port: 8083
  forward-headers-strategy: framework
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}